# workaround for https://github.com/travis-ci/travis-ci/issues/7884 
sudo: required

language: java
dist: trusty

jdk:
  - oraclejdk8
#  - oraclejdk7 (not currently working on Travis)
  - openjdk8
  - openjdk7
  - openjdk6
env:
  - TEST_COMMAND="ant test"
  - TEST_COMMAND="travis_wait 50 ant diehard_stdout"
addons:
  apt:
    packages:
      - dieharder
script:
  - "$TEST_COMMAND"
