# workaround for https://github.com/travis-ci/travis-ci/issues/2839 
env:
  - JAVA_HOME=/

language: java
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
  - openjdk6
addons:
  apt:
    packages:
      - dieharder
script:
  - ant test
  - ant diehard
