# workaround for https://github.com/travis-ci/travis-ci/issues/7884 
sudo: required

language: java
dist: trusty

jdk:
  - oraclejdk8
#  - oraclejdk7 (not currently working on Travis)
  - openjdk8
  - openjdk7
#  - openjdk6 (not currently working on Travis)
env:
  - ANT_TARGET="test"
  - ANT_TARGET="diehard_aes_1"
  - ANT_TARGET="diehard_aes_2"
  - ANT_TARGET="diehard_automaton_1"
  - ANT_TARGET="diehard_automaton_2"
  - ANT_TARGET="diehard_cmwc_1"
  - ANT_TARGET="diehard_cmwc_2"
  - ANT_TARGET="diehard_mersenne_1"
  - ANT_TARGET="diehard_mersenne_2"
  - ANT_TARGET="diehard_xor_1"
  - ANT_TARGET="diehard_xor_2"
  - ANT_TARGET="diehard_java_1"
  - ANT_TARGET="diehard_java_2"
addons:
  apt:
    packages:
      - dieharder
script:
  - travis_wait 50 ant "$ANT_TARGET"
