# workaround for https://github.com/travis-ci/travis-ci/issues/7884 
sudo: required

language: java
dist: trusty

jdk:
  - oraclejdk8
#  - oraclejdk7 (not currently working on Travis)
  - openjdk8
  - openjdk7
#  - openjdk6 (not currently working on Travis)
env:
  - TEST_COMMAND="ant test"
  - TEST_COMMAND="travis_wait 50 ant diehard_aes"
  - TEST_COMMAND="travis_wait 50 ant diehard_automaton"
  - TEST_COMMAND="travis_wait 50 ant diehard_cmwc"
  - TEST_COMMAND="travis_wait 50 ant diehard_mersenne"
  - TEST_COMMAND="travis_wait 50 ant diehard_xor"
  - TEST_COMMAND="travis_wait 50 ant diehard_java"
addons:
  apt:
    packages:
      - dieharder
script:
  - "$TEST_COMMAND"
