# workaround for https://github.com/travis-ci/travis-ci/issues/7884 
sudo: required

language: java
dist: trusty

jdk:
  - oraclejdk8
#  - oraclejdk7 (not currently working on Travis)
  - openjdk8
  - openjdk7
  - openjdk6
addons:
  apt:
    packages:
      - dieharder
script:
  - ant test
  - travis_wait ant diehard_stdout
